<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE chords [
	<!ELEMENT chords (chord+)>
	<!ELEMENT chord (shortname,longname,semitone+)>
	<!ELEMENT shortname (#PCDATA)>
	<!ELEMENT longname (#PCDATA)>
	<!ELEMENT semitone (#PCDATA)>
	<!ATTLIST chords title CDATA #IMPLIED>
	<!ATTLIST chord id ID #REQUIRED>
]>

<chords title="chord numbers">
	
	<chord id="M">
	    <shortname>M</shortname>
	    <longname>major triad</longname>
        <semitone>4</semitone>
        <semitone>7</semitone>
	</chord>
	<chord id="7">
	    <shortname>7</shortname>
	    <longname>seventh</longname>
        <semitone>4</semitone>
        <semitone>7</semitone>
        <semitone>10</semitone>
	</chord>
	<chord id="M7">
	    <shortname>M7</shortname>
	    <longname>major seventh</longname>
        <semitone>4</semitone>
        <semitone>7</semitone>
	        <semitone>11</semitone>
	</chord>
	<chord id="6">
	    <shortname>6</shortname>
   	    <longname>sixth</longname>
        <semitone>4</semitone>
        <semitone>7</semitone>
        <semitone>9</semitone>
	</chord>
	<chord id="m">
	    <shortname>m</shortname>
	    <longname>minor triad</longname>
        <semitone>3</semitone>
        <semitone>7</semitone>
	</chord>
	<chord id="mM7">
	    <shortname>mM7</shortname>
	    <longname>minor major seventh</longname>
        <semitone>3</semitone>
        <semitone>7</semitone>
        <semitone>11</semitone>
	</chord>
	<chord id="m6">
	    <shortname>m6</shortname>
	    <longname>minor sixth</longname>
        <semitone>3</semitone>
        <semitone>7</semitone>
        <semitone>9</semitone>
	</chord>
	<chord id="m7">
	    <shortname>m7</shortname>
  	    <longname>minor seventh</longname>
        <semitone>3</semitone>
        <semitone>7</semitone>
        <semitone>10</semitone>
	</chord>
	<chord id="m7(flat5)">
	    <shortname>m7(flat5)</shortname>
	    <longname>minor seventh on flat five</longname>
        <semitone>3</semitone>
        <semitone>6</semitone>
        <semitone>10</semitone>
	</chord>
	<chord id="sus4">
	    <shortname>sus4</shortname>
	    <longname>suspended fourth</longname>
        <semitone>5</semitone>
        <semitone>7</semitone>
	</chord>
	<chord id="7sus4">
	    <shortname>7sus4</shortname>
  	    <longname>seventh suspended fourth</longname>    
        <semitone>5</semitone>
        <semitone>7</semitone>
   	    <semitone>10</semitone>
	</chord>
	<chord id="dim">
	    <shortname>dim</shortname>
	    <longname>diminished triad</longname>
        <semitone>3</semitone>
        <semitone>6</semitone>
	</chord>
	<chord id="dim7">
	    <shortname>dim7</shortname>
	    <longname>diminished seventh</longname>
        <semitone>3</semitone>
        <semitone>6</semitone>
        <semitone>9</semitone>
	</chord>
	<chord id="aug">
	    <shortname>aug</shortname>
	    <longname>augumented triad</longname>
        <semitone>4</semitone>
        <semitone>8</semitone>
	</chord>
	<chord id="aug7">
	    <shortname>aug7</shortname>
	    <longname>augumented seventh</longname>
        <semitone>4</semitone>
        <semitone>8</semitone>
       	<semitone>10</semitone>
	</chord>

</chords>